const products = [
  {
    _id: '1',
    name: 'Airpods Wireless Bluetooth Headphones',
    image: '/images/airpods.jpg',
    description:
      'Bluetooth technology lets you connect it with compatible devices wirelessly High-quality AAC audio offers immersive listening experience Built-in microphone allows you to take calls while working',
    brand: 'Apple',
    category: 'Electronics',
    price: 89.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '2',
    name: 'iPhone 11 Pro 256GB Memory',
    image: '/images/phone.jpg',
    description:
      'Introducing the iPhone 11 Pro. A transformative triple-camera system that adds tons of capability without complexity. An unprecedented leap in battery life',
    brand: 'Apple',
    category: 'Electronics',
    price: 599.99,
    countInStock: 7,
    rating: 4.0,
    numReviews: 8,
  },
  {
    _id: '3',
    name: 'Cannon EOS 80D DSLR Camera',
    image: '/images/camera.jpg',
    description:
      'Characterized by versatile imaging specs, the Canon EOS 80D further clarifies itself using a pair of robust focusing systems and an intuitive design',
    brand: 'Cannon',
    category: 'Electronics',
    price: 929.99,
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: '4',
    name: 'Sony Playstation 4 Pro White Version',
    image: '/images/playstation.jpg',
    description:
      'The ultimate home entertainment center starts with PlayStation. Whether you are into gaming, HD movies, television, music',
    brand: 'Sony',
    category: 'Electronics',
    price: 399.99,
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: '5',
    name: 'Logitech G-Series Gaming Mouse',
    image: '/images/mouse.jpg',
    description:
      'Get a better handle on your games with this Logitech LIGHTSYNC gaming mouse. The six programmable buttons allow customization for a smooth playing experience',
    brand: 'Logitech',
    category: 'Electronics',
    price: 49.99,
    countInStock: 7,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id: '6',
    name: 'Amazon Echo Dot 3rd Generation',
    image: '/images/alexa.jpg',
    description:
      'Meet Echo Dot - Our most popular smart speaker with a fabric design. It is our most compact smart speaker that fits perfectly into small space',
    brand: 'Amazon',
    category: 'Electronics',
    price: 29.99,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  }, {
    _id: '7',
    name: 'Apple MacBook Air 13" Core i5 1,6 GHz - SSD 128 Go RAM 8 Go AZERTY',
    image: '/images/Macbook.jpg',
    description:
      "Enjoy a Stunning Retina Display with True Tone Technology Core i5 processor clocked at 1.6 Ghz Storage type: 128GB SSD Connector: Type C, Bluetooth, webcam",
    brand: 'Apple',
    category: 'Electronics',
    price: 762.99,
    countInStock: 11,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '8',
    name: 'New Apple MacBook Pro with Apple M1 Chip (13-inch, 8GB RAM, 256GB SSD) - Space Grey (Latest Model)',
    image: '/images/mp.jpg',
    description:
      "Apple-designed M1 chip for a giant leap in CPU, GPU, and machine learning performanceGet more done with up to 20 hours of battery life, the longest ever in a Mac8-core CPU delivers up to 2.8x faster performance to fly through workflows quicker than ever8-core GPU with up to 5x faster graphics for graphics-intensive apps and games16-core Neural Engine for advanced machine learning8GB of unified memory so everything you do is fast and fluidSuperfast SSD storage launches apps and opens files in an instant",
   brand: 'Apple',category: 'Electronics',
    price: 1000.99,
    countInStock: 13,
    rating: 4.5,
    numReviews: 8,
  },

  {
    _id: '9',
    name: 'Apple MacBook Air (13-inch, 1.1GHz quad-core 10th-generation Intel Core i5 processor, 8GB RAM, 512GB) - Space Grey (Previous Model)',
    image: '/images/mac2.jpg',
    description:
      "Stunning 13.3-inch Retina display with True Tone technologyBacklit Magic Keyboard and Touch IDTenth-generation Intel Core i5 processorIntel Iris Plus GraphicsFast SSD storage8GB of memoryStereo speakers with wider stereo sound",
    brand: 'Apple',
    category: 'Electronics',
    price: 1762.99,
    countInStock: 11,
    rating: 3,
    numReviews: 21,
  },
  {
    _id: '10',
    name: 'Apple MacBook Pro (13-inch, 8GB RAM, 256GB SSD Storage, Magic Keyboard) - Space Grey (Previous Model)',
    image: '/images/mac1.jpg',
    description:
      "Eighth-generation quad-core Intel Core i5 processor Brilliant Retina display with True Tone technologyBacklit Magic KeyboardTouch Bar and Touch IDIntel Iris Plus Graphics 645Ultra-fast SSDTwo Thunderbolt 3 (USB-C) ports",
   brand: 'Apple',category: 'Electronics',
    price: 1000.99,
    countInStock: 13,
    rating: 4.5,
    numReviews: 8,
  },
  {
    _id: '11',
    name: 'Apple Magic Keyboard (Wireless, Rechargable) (British English) - Silver',
    image: '/images/keyboard.jpg',
    description:
      "Features an extended layout, with document navigation controls for quick scrolling and full-size arrow keys for gamingA scissor mechanism beneath each key allows for increased stability The battery is incredibly long-lasting - it will power your keyboard for about a month or more between charges Magic Keyboard provides a remarkably comfortable and precise typing experience The Magic Keyboard pairs automatically with your Mac",
   brand: 'Apple',category: 'Electronics',
    price: 1200.99,
    countInStock:0,
    rating: 1.5,
    numReviews: 17,
  },
  {
    _id: '12',
    name: 'New Apple Mac mini with Apple M1 Chip (8GB RAM, 512GB SSD)',
    image: '/images/aad.jpg',
    description:
      "Apple-designed M1 chip for a giant leap in CPU, GPU, and machine learning performance 8-core CPU packs up to 3x faster performance to fly through workflows quicker than ever* 8-core GPU with up to 6x faster graphics for graphics-intensive apps and games*16-core Neural Engine for advanced machine learning 8GB of unified memory so everything you do is fast and fluidSuperfast SSD storage launches apps and opens files in an instantAdvanced cooling system sustains breakthrough performance",
   brand: 'Apple',category: 'Electronics',
    price: 1700.99,
    countInStock:10,
    rating: 3.5,
    numReviews: 9,
  },
]

export default products
